### ISSUE TITLE
Manage group manager properties

### ISSUE THREAD

**Issue by MichalWirth** [lithnet/googleapps-managementagent#50]
Hi @ryannewington,

I am trying to verify if it would be possible to manage some additional attributes for group managers in Google. I am thinking about delivery settings attribute which seems to be tied to a specific instance of manager in a group, and not to group or user only.
Here is the API method: https://developers.google.com/admin-sdk/directory/v1/reference/members/update
Is it possible to handle this using Google Apps MA?

Michał

**Comment by ryannewington** [comment]
Hi @MichalWirth,

That's a really tricky one. To be honest, supporting owners/managers/members on its own was a pain, due to the differences in the way that FIM operations with its flat schema and referential integrity, compared to google and its nested schema with properties on reference objects.

Unfortunately, I can't see a way to add support for these settings in the MA.

**Comment by MichalWirth** [comment]
Hi @Ryan Newington<mailto:notifications@github.com>,

Thank you for confirming. I was suspecting that this might be impossible.

Seems I will have to handle this one using PowerShell.

Thanks a lot.

[cid:94224a52-9db1-4585-baf5-93cefa5f903c.jpg]
Michal Wirth
Digital Advisor
Identity, Security & Infrastructure
M: +48 601 076 708
 [cid:predica-logo-70x26_4d82a433-0be9-4212-8340-ab5554851c6d.jpg]  <https://predica.pl/>


Sign up for our webinar: Boost your Enterprise Security with Identity Governance <https://www.omada.net/en-us/more/news-events/events/predica-webinar?utm_source=predica&utm_medium=footer-link>
